version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
  radon:
    enabled: true
    config:
      python_version: 3
      threshold: "A"
  pep8:
    enabled: true
    config:
      python_version: 3
      max_line_length: 100
      statistics: true
      count: False
      show_source: true
      checks:
        E402:
          enabled: false
        E501:
          enabled: false
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - test_*
exclude_paths:
  - ".*"
  - "test_*"
  - "dnslist.txt"
  - "*.md"
  - "LICENSE"
