sudo: false
dist: trusty
language: python
python:
  - "3.6"
env:
  global:
    - GIT_ASK_YESNO='false'
    - PYTHONIOENCODING='utf-8'

install:
  - "pip install --upgrade pip"
  - "pip install -e . --upgrade --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"
  - 'pip install -e "$(pwd)" --upgrade'
  - 'pipenv install --system --dev'

script:
  - 'pipenv run time pytest -v'
