language: python
matrix:
  include:
    - python: 3.3
      env:
      - TOXENV=py33
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
    - python: pypy3
      env:
      - TOXENV=pypy3
  allow_failures:
    - env: TOXENV=py33

install:
  - pip install tox coveralls pytest flake8 pylint
script:
  - tox
after_success:
  - coveralls
